import { useState, useEffect } from 'react';
import {
  Card,
  Title,
  Text,
  Group,
  Badge,
  Stack,
  Button,
  Alert,
  Box,
  Grid,
  SimpleGrid,
  List,
  ThemeIcon
} from '@mantine/core';
import {
  IconQrcode,
  IconDeviceMobile,
  IconDownload,
  IconShare,
  IconCopy,
  IconRefresh,
  IconCheck,
  IconAlertCircle,
  IconExternalLink
} from '@tabler/icons-react';
import { analyticsService } from '../services/analytics';

interface QRCodeGeneratorWithAnalyticsProps {
  compilationId: string;
  mobileUrl?: string;
  title?: string;
  description?: string;
  showAnalytics?: boolean;
  onQRGenerated?: (qrData: any) => void;
}

export default function QRCodeGeneratorWithAnalytics({
  compilationId,
  mobileUrl,
  title = 'QR Code Generator',
  description,
  showAnalytics = true,
  onQRGenerated
}: QRCodeGeneratorWithAnalyticsProps) {
  const [qrCodeUrl, setQrCodeUrl] = useState<string | null>(null);
  const [qrCodeData, setQrCodeData] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedAt, setGeneratedAt] = useState<Date | null>(null);
  const [scanCount, setScanCount] = useState(0);
  const [analyticsEnabled, setAnalyticsEnabled] = useState(true);

  // Generate mobile URL if not provided
  const getMobileUrl = () => {
    return mobileUrl || `https://mobile.tams.demo/play/${compilationId}`;
  };

  // Generate QR code
  const generateQRCode = async () => {
    if (isGenerating) return;

    try {
      setIsGenerating(true);
      
      // Track QR generation in analytics
      if (analyticsEnabled) {
        analyticsService.trackQRScan(compilationId);
      }

      // Simulate QR code generation (in real app, this would call a QR service)
      const url = getMobileUrl();
      setQrCodeData(url);
      
      // Create a mock QR code image (in real app, this would be generated by a service)
      const mockQRCodeUrl = `data:image/svg+xml;base64,${btoa(`
        <svg width="200" height="200" xmlns="http://www.w3.org/2000/svg">
          <rect width="200" height="200" fill="white"/>
          <text x="100" y="100" text-anchor="middle" font-family="Arial" font-size="12" fill="black">
            QR Code Demo
          </text>
          <text x="100" y="120" text-anchor="middle" font-family="Arial" font-size="8" fill="gray">
            ${compilationId}
          </text>
        </svg>
      `)}`;
      
      setQrCodeUrl(mockQRCodeUrl);
      setGeneratedAt(new Date());
      setScanCount(prev => prev + 1);

      // Notify parent component
      onQRGenerated?.({
        compilationId,
        qrCodeUrl: mockQRCodeUrl,
        mobileUrl: url,
        generatedAt: new Date()
      });

    } catch (error) {
      console.error('Failed to generate QR code:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  // Copy mobile URL to clipboard
  const copyMobileUrl = async () => {
    try {
      await navigator.clipboard.writeText(getMobileUrl());
      // Track copy action
      if (analyticsEnabled) {
        analyticsService.trackQRScan(compilationId);
      }
    } catch (error) {
      console.error('Failed to copy URL:', error);
    }
  };

  // Download QR code
  const downloadQRCode = () => {
    if (!qrCodeUrl) return;

    const link = document.createElement('a');
    link.href = qrCodeUrl;
    link.download = `qr_code_${compilationId}.svg`;
    link.click();
  };

  // Share QR code
  const shareQRCode = async () => {
    if (!qrCodeUrl) return;

    try {
      if (navigator.share) {
        await navigator.share({
          title: 'Video QR Code',
          text: `Scan this QR code to access the video compilation: ${compilationId}`,
          url: getMobileUrl()
        });
      } else {
        // Fallback to copying URL
        await copyMobileUrl();
      }
    } catch (error) {
      console.error('Failed to share QR code:', error);
    }
  };

  // Auto-generate QR code on mount
  useEffect(() => {
    if (!qrCodeUrl) {
      generateQRCode();
    }
  }, [compilationId]);

  return (
    <Card withBorder p="md">
      <Stack gap="md">
        {/* Header */}
        <Group justify="space-between">
          <Box>
            <Title order={4}>{title}</Title>
            {description && (
              <Text size="sm" c="dimmed">
                {description}
              </Text>
            )}
          </Box>
          <Group>
            <Badge color="blue" variant="light">
              {compilationId}
            </Badge>
            {analyticsEnabled && (
              <Badge color="green" variant="light">
                Analytics Active
              </Badge>
            )}
          </Group>
        </Group>

                {/* QR Code Display */}
        <SimpleGrid cols={{ base: 1, md: 2 }} spacing="lg">
          <Card withBorder p="md">
            <Stack gap="md" align="center">
              <Group>
                <IconQrcode size={24} />
                <Title order={5}>QR Code</Title>
              </Group>

              {qrCodeUrl ? (
                <Box
                  style={{
                    width: '200px',
                    height: '200px',
                    border: '2px solid #e0e0e0',
                    borderRadius: '8px',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    backgroundColor: 'white'
                  }}
                >
                  <img
                    src={qrCodeUrl}
                    alt="QR Code"
                    style={{
                      width: '180px',
                      height: '180px',
                      objectFit: 'contain'
                    }}
                  />
                </Box>
              ) : (
                <Box
                  style={{
                    width: '200px',
                    height: '200px',
                    border: '2px dashed #e0e0e0',
                    borderRadius: '8px',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    backgroundColor: '#f8f9fa'
                  }}
                >
                  <Text size="sm" c="dimmed">
                    Generating QR Code...
                  </Text>
                </Box>
              )}

              <Group>
                <Button
                  size="sm"
                  variant="light"
                  onClick={generateQRCode}
                  loading={isGenerating}
                  leftSection={<IconRefresh size={14} />}
                >
                  Regenerate
                </Button>
                {qrCodeUrl && (
                  <>
                    <Button
                      size="sm"
                      variant="light"
                      onClick={downloadQRCode}
                      leftSection={<IconDownload size={14} />}
                    >
                      Download
                    </Button>
                    <Button
                      size="sm"
                      variant="light"
                      onClick={shareQRCode}
                      leftSection={<IconShare size={14} />}
                    >
                      Share
                    </Button>
                  </>
                )}
              </Group>

              {generatedAt && (
                <Text size="xs" c="dimmed">
                  Generated: {generatedAt.toLocaleString()}
                </Text>
              )}
            </Stack>
          </Card>
          
          <Card withBorder p="md">
            <Stack gap="md">
              <Group>
                <IconDeviceMobile size={20} />
                <Title order={5}>Mobile Access</Title>
              </Group>

              <Box>
                <Text size="sm" fw={500}>Mobile URL:</Text>
                <Text size="xs" style={{ 
                  wordBreak: 'break-all',
                  backgroundColor: '#f8f9fa',
                  padding: '8px',
                  borderRadius: '4px',
                  fontFamily: 'monospace'
                }}>
                  {getMobileUrl()}
                </Text>
              </Box>

              <Group>
                <Button
                  size="sm"
                  variant="light"
                  onClick={copyMobileUrl}
                  leftSection={<IconCopy size={14} />}
                >
                  Copy URL
                </Button>
                <Button
                  size="sm"
                  variant="light"
                  component="a"
                  href={getMobileUrl()}
                  target="_blank"
                  leftSection={<IconExternalLink size={14} />}
                >
                  Test Link
                </Button>
              </Group>

              <Box>
                <Text size="sm" fw={500}>QR Code Stats:</Text>
                <List size="sm" spacing="xs">
                  <List.Item>
                    <Text size="sm">• Scans: {scanCount}</Text>
                  </List.Item>
                  <List.Item>
                    <Text size="sm">• Device: Mobile optimized</Text>
                  </List.Item>
                  <List.Item>
                    <Text size="sm">• Access: Time-limited tokens</Text>
                  </List.Item>
                </List>
              </Box>
            </Stack>
          </Card>
        </SimpleGrid>

        {/* Analytics Info */}
        {showAnalytics && (
          <Alert icon={<IconCheck size={16} />} color="blue" variant="light">
            <Text size="sm">
              <strong>QR Code Analytics:</strong> This QR code generator tracks scan events, 
              device types, and access patterns. Data helps optimize mobile video delivery 
              and user experience.
            </Text>
            <Group mt="xs">
              <Button
                size="xs"
                variant="light"
                onClick={() => setAnalyticsEnabled(!analyticsEnabled)}
              >
                {analyticsEnabled ? 'Disable' : 'Enable'} Analytics
              </Button>
              <Text size="xs" c="dimmed">
                Session ID: {sessionStorage.getItem('tams_session_id')?.slice(0, 8)}...
              </Text>
            </Group>
          </Alert>
        )}

        {/* Usage Instructions */}
        <Card withBorder p="md">
          <Stack gap="md">
            <Title order={5}>How to Use</Title>
            <SimpleGrid cols={{ base: 1, md: 2 }} spacing="lg">
              <List size="sm" spacing="xs">
                <List.Item>
                  <Text size="sm">1. Scan the QR code with your mobile device</Text>
                </List.Item>
                <List.Item>
                  <Text size="sm">2. The mobile URL will open automatically</Text>
                </List.Item>
                <List.Item>
                  <Text size="sm">3. Video will play in mobile-optimized player</Text>
                </List.Item>
              </List>
              <List size="sm" spacing="xs">
                <List.Item>
                  <Text size="sm">• QR codes are valid for 24 hours</Text>
                </List.Item>
                <List.Item>
                  <Text size="sm">• Mobile player is touch-optimized</Text>
                </List.Item>
                <List.Item>
                  <Text size="sm">• Analytics track scan and playback events</Text>
                </List.Item>
              </List>
            </SimpleGrid>
          </Stack>
        </Card>
      </Stack>
    </Card>
  );
}
